# Generated by Django 5.1.6 on 2025-03-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil')], default='CAD', max_length=20),
        ),
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='p_apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='s_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jugador',
            name='subcategoria',
            field=models.CharField(choices=[('PREBEN', 'Prebenjamín'), ('BEN', 'Benjamín'), ('ALE', 'Alevín'), ('INF', 'Infantil'), ('CAD', 'Cadete'), ('JUV', 'Juvenil')], default='BEN', max_length=6),
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='jugadores.carpeta')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='jugadores.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/pdfs')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='jugadores.carpeta')),
            ],
        ),
    ]
