# Generated by Django 5.1.6 on 2025-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_alter_jugador_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
    ]
