# Generated by Django 5.1.6 on 2025-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_jugador_equipo_alter_jugador_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='archivo',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
