# Generated by Django 5.1.6 on 2025-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0006_evento_alter_jugador_imagen_alter_pdf_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
