# Generated by Django 5.1.6 on 2025-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0008_pdf_nombre_pdf_url_alter_jugador_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='evento',
            name='equipo1',
            field=models.CharField(default='Portuense F.C.', max_length=25),
        ),
        migrations.AddField(
            model_name='evento',
            name='equipo2',
            field=models.CharField(default='', max_length=25),
        ),
    ]
