# Generated by Django 5.1.6 on 2025-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0009_rename_fecha_inicio_evento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='equipo1',
            field=models.CharField(default='Portuense F.C.', max_length=45),
        ),
        migrations.AlterField(
            model_name='evento',
            name='equipo2',
            field=models.CharField(default='', max_length=45),
        ),
    ]
