# Generated by Django 5.1.6 on 2025-03-31 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0010_alter_evento_equipo1_alter_evento_equipo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excels/')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excels', to='jugadores.foldergroup')),
            ],
        ),
    ]
